version: '3'

services:
  frontend:
    image: eeacms/freshwater-frontend:develop
    user: "node:node"
    volumes:
    - freshwater_devel_addons:/opt/frontend/src/addons:rw
    depends_on:
    - ploneapi
    environment:
      RAZZLE_API_PATH: "http://localhost:${BACKEND_PORT:-8080}/${SITE_NAME:-Plone}"
      RAZZLE_INTERNAL_API_PATH: "http://ploneapi:8080/${SITE_NAME:-Plone}"
      PORT: "${FRONTEND_PORT:-3000}"
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
      - "${FRONTEND_PORT_NEXT:-3001}:${FRONTEND_PORT_NEXT:-3001}"
      - "${FRONTEND_ANALYZE_PORT:-8888}:${FRONTEND_ANALYZE_PORT:-8888}"
    entrypoint: sh -c "tail -f /dev/null"
    # ports:
    # - "${FRONTEND:-3000}:3000"
    # environment:
    #   API_PATH: "http://localhost:${BACKEND:-8080}/Plone"
    #   INTERNAL_API_PATH: "http://ploneapi:${BACKEND:-8080}/Plone"

  ploneapi:
    # image: eeacms/plonesaas-devel
      # CORS_ALLOW_ORIGIN: "http://localhost:3000,http://127.0.0.1:3000,http://localhost:${FRONTEND:-8000},http://127.0.0.1:${FRONTEND:-8000}"
    build: ./backend
    ports:
    - "${BACKEND_PORT:-8080}:8080"
    environment:
      CORS_ALLOW_ORIGIN: "http://localhost:${FRONTEND_PORT:-3000}"
    depends_on:
    - memcached
    volumes:
    - ./data:/data
    - ./backend/src:/plone/instance/src
    entrypoint: sh -c "tail -f /dev/null"

  memcached:
    image: memcached
    command:
    - "-m"
    - "512"

volumes:
  data:
    driver: local
  freshwater_devel_addons:
    driver: local
